MODULE Module3
USE Module5, ONLY : Module5Subroutine2
IMPLICIT NONE

PRIVATE :: Module3Subroutine4, Module3Subroutine5

CONTAINS
 
SUBROUTINE Module3Subroutine1

!SUBROUTINE BODY

END SUBROUTINE Module3Subroutine1

SUBROUTINE Module3Subroutine2

!SUBROUTINE BODY

END SUBROUTINE Module3Subroutine2

SUBROUTINE Module3Subroutine3

!SUBROUTINE BODY

END SUBROUTINE Module3Subroutine3

SUBROUTINE Module3Subroutine4

!SUBROUTINE BODY

END SUBROUTINE Module3Subroutine4

SUBROUTINE Module3Subroutine5

!SUBROUTINE BODY

END SUBROUTINE Module3Subroutine5

END MODULE Module3
